### ISSUE TITLE
Show on preview

### ISSUE THREAD

**Issue by ThisIsMyFavouriteJar** [oooholdings/nova-password-generator#10]
Love this password generator so far! 

Was wondering if you are considering extending functionality for the preview page as well? 
I would like to give my users the possibility to copy an API key from the preview page, and perhaps there are some other use cases where this might be useful. I guess only the copy field (and the actual value) needs to be displayed on preview!

Thank you!

**Comment by btrsco** [comment]
@ThisIsMyFavouriteJar thanks for the support and feature suggestion. 

I will take a look and see what I can do. The copy feature on detail / index / preview would be nice, as well as maybe a show button.

I’ll probably get to this next weekend, possibly sooner if I have some free time! Thanks again

**Comment by btrsco** [comment]
Sorry for the delay @ThisIsMyFavouriteJar,
I have finished the feature you requested. Please take a look at the [readme.md#index-and-detail-view](https://github.com/oooholdings/nova-password-generator#index-and-detail-view=) for details on the methods that enable this feature. Let me know if this works out for you or come across any bugs feel free to open a new issue (I'm the only one testing so some stuff might slip through).

If you found me on [Nova Packages](https://novapackages.com/packages/outofoffice/password-generator), I'd appreciate if you could leave a review of your experience with this package.
