### ISSUE TITLE
Help text not showing correctly.

### ISSUE THREAD

**Issue by josemanuelsh** [oooholdings/nova-password-generator#12]
Hey!

Thanks for the great work!

Just a little bug when including help text in the field.

![image](https://user-images.githubusercontent.com/7245728/167230228-000d5951-cabf-4d6c-9342-2d5a333f7b76.png)

And a request, not a big deal for the project I am working on now, but it may be needed in the future or by other developers...

Can you make it translatable?

If we could have some LANG file to change the texts, it would make it a perfect field.

Thanks!

**Comment by btrsco** [comment]
Hey @josemanuelsh, I'll look into fixing the visual bug with the help text being displayed along side the field. As for the feature request I have thought about implementing this in the future, so it's on the backlog right now but haven't needed to actually implement it - until now. 

I'll try to work on this stuff through out this next week and update you when I have fixed the bug, as the lang files aren't mission critical for you at this point I'll start working on it soon after the bug fix! Thanks!

**Comment by btrsco** [comment]
<img width="860" alt="Screenshot 2022-05-30 at 21 23 56@2x" src="https://user-images.githubusercontent.com/1373528/171092462-d0a51df6-6d85-464c-b0de-b23567b23642.png">
@josemanuelsh I have fixed the layout issue with help text and any error text. Thanks for reporting this issue!
