### ISSUE TITLE
Copy field with Custom Field Name

### ISSUE THREAD

**Issue by jordansitbon** [oooholdings/nova-password-generator#13]
Hey,

I use this package in my project for generate an API Key 😁 .
Your package is awesome!
But... When i copy the value with the button, the toast message show `Password has been copied` and not `{Field Name} has been copied`.

**Comment by btrsco** [comment]
Hey @jordansitbon, good catch! I will plan on removing all references to "password" within the strings the generator displays to users. Please allow me a week or so to implement this, thank you for the suggestion!

**Comment by btrsco** [comment]
@jordansitbon I have changed references to "Password" to "Value" for now, still working on implementing a language file. I'll let you know once that solution has been implemented.

**Comment by btrsco** [comment]
@jordansitbon the field now uses its name within the other strings, like "Copy Password" would turn to "Copy Access Token" if your field was named "Access Token". I also added the ability to customize all the strings themselves so you can change the terminology.

I hope this works as you expect, make sure to update your composer dependencies to get the new release.
