### ISSUE TITLE
updateRules nullable not working [bug]

### ISSUE THREAD

**Issue by jodhaakbar** [oooholdings/nova-password-generator#14]
hi @btrsco ,

my code :

```
 PasswordGenerator::make('Password')
                ->onlyOnForms()
                ->creationRules('required', Rules\Password::defaults())
                ->updateRules('nullable', Rules\Password::defaults()),
```

when i update the user, and leave blank on password field, PasswordGenerator always update the password field value.

i am using nova 4.

**Comment by btrsco** [comment]
Thanks for the bug report,

@jodhaakbar when you update the user is this only visually updating in the PasswordGenerator field and/or saving a new value to the database? In the meantime I'll take a look and see if I can duplicate and fix this issue.

**Comment by jodhaakbar** [comment]
hi @btrsco 

i checked on database, password field fill with new value, everytime update the nova form.

**Comment by btrsco** [comment]
@jodhaakbar thanks for double checking for me, I'm working on fixing some old issues and I'll get to this one later tonight. I'll reach out once the package has been updated.

**Comment by btrsco** [comment]
@jodhaakbar this bug has been fixed and also added a new chain method `saveAsPlainText()` that will disable the hashing of the field value when saving to the database. Enjoy the update!
