### ISSUE TITLE
show/hide password is showing wrong icon and text for the state

### ISSUE THREAD

**Issue by chrillep** [oooholdings/nova-password-generator#19]
- when password is hidden it should say show password and have icon for show
- when password is visible it should say hide password and have icon for hide

<img width="533" alt="Skärmavbild 2022-12-05 kl  13 28 18" src="https://user-images.githubusercontent.com/1267931/205637635-d282c38a-97c6-4897-bce4-2397094fbc8b.png">
<img width="630" alt="Skärmavbild 2022-12-05 kl  13 28 05" src="https://user-images.githubusercontent.com/1267931/205637639-13abb042-7ef7-410d-bd3c-68c8dce02565.png">

**Comment by btrsco** [comment]
@chrillep Good catch! 
The icon state seems like its fine, looks like I just need to change the tooltip label. I'll get to this soon.

**Comment by chrillep** [comment]
@btrsco yeah your right :) 
the criterias are correct tho haha

- when password is hidden it should say show password and have icon for show
- when password is vissible it should say hide password and have icon for hide

**Comment by btrsco** [comment]
Thank you for your contribution @chrillep, sorry it took so long to get to this. I have been way too busy recently to get to this sooner. This has been implemented in [v1.8.0](https://github.com/oooholdings/nova-password-generator/releases/tag/v1.8.0)
