### ISSUE TITLE
Show value in field on update view

### ISSUE THREAD

**Issue by arturasfrontit** [oooholdings/nova-password-generator#30]
I'm using this field for voucher code, where is no way, to pass value in form it always empty or filling random generated value.

![image](https://github.com/oooholdings/nova-password-generator/assets/131424569/0ba7e46d-22a6-4d20-8c21-a6c6e7723a4c)

My current solution:

Resource
```
Text::make(__('Code'), 'code')
    ->sortable()
    ->readonly()
    ->rules('required', 'max:50'),

PasswordGenerator::make( __('Generate code'), 'generate_code')
    ->help(__('Leave empty if `'. $this->code . '` suitable'))
    ->showPassword()
    ->excludeSymbols()
    ->excludeSimilar()
    ->length(8)
    ->onlyOnForms()
    ->rules('nullable', 'max:50'),
```
Observer
```
    public function saving(Voucher $voucher)
    {
        if (! $this->request->editing) {
            return;
        }

        if ($this->request->generate_code) {
            unset($voucher->generate_code);
            $voucher->code = $this->request->generate_code;
        }
    }
```

**Comment by btrsco** [comment]
Hey @arturasfrontit and @mostafaznv,

Thanks for reporting this, sorry for the late response. Fortunately there is a method you could use already implemented that solves this issue. 

`->showValueOnUpdate( bool $show = true )` should be what you're looking for, you can read more about it and similar methods on the [readme.md](https://github.com/oooholdings/nova-password-generator#index-and-detail-view) file, in the **Index and Detail View** section. If there is a specific reason why this doesn't fix the issue for you, let me know and we can hash out a possible solution. Otherwise I'll consider this issue resolve and close it soon.

**Comment by arturasfrontit** [comment]
> Hey @arturasfrontit and @mostafaznv,
> 
> Thanks for reporting this, sorry for the late response. Fortunately there is a method you could use already implemented that solves this issue.
> 
> `->showValueOnUpdate( bool $show = true )` should be what you're looking for, you can read more about it and similar methods on the [readme.md](https://github.com/oooholdings/nova-password-generator#index-and-detail-view) file, in the **Index and Detail View** section. If there is a specific reason why this doesn't fix the issue for you, let me know and we can hash out a possible solution. Otherwise I'll consider this issue resolve and close it soon.

I tried `showValueOnUpdate` method before sending issue it doesn't show value

```
PasswordGenerator::make(__('Generate code'), 'code')
    ->help(__('Leave empty if :code suitable', ['code' => $this->code]))
    ->showValueOnUpdate()
    ->showPassword()
    ->excludeSymbols()
    ->excludeSimilar()
    ->length(8)
    ->onlyOnForms()
    ->rules('nullable', 'max:50'),
```

UPDATE: for some reason it showing it now, but column is empty on index

Also how remove password cast?

```
set `code` = $2y$10$0SYtFzXQEEM6QbBtO6cpM.yZOgMdiCvJPqn.vWckq6bKLttpm5Kki
```

**Comment by btrsco** [comment]
Glad it's working for you now! There is another method you want to add to the chain that will fix the next issue:

> Also how remove password cast?
> 
> ```
> set `code` = $2y$10$0SYtFzXQEEM6QbBtO6cpM.yZOgMdiCvJPqn.vWckq6bKLttpm5Kki
> ```

The method is `->saveAsPlainText( bool $plainText = true )`, this ensures that the value is always saved as plain-text. You can read more about this method [here](https://github.com/oooholdings/nova-password-generator#other-methods). Let me know if this also fixes the issue where the code is no longer showing on the index view.

**Comment by arturasfrontit** [comment]
Thank you!

**Comment by arturasfrontit** [comment]
Final code if someone need:
```
PasswordGenerator::make(__('Code'), 'code')
    ->saveAsPlainText()
    ->showValueOnUpdate()
    ->showPassword()
    ->excludeSymbols()
    ->excludeSimilar()
    ->length(8)
    ->onlyOnForms()
    ->rules('required', 'max:50'),
```
